spring:
  application.name: intverse-kafka-producer
  kafka:
#    bootstrap-servers: redpanda.intverse-rp-ns:32000
#    producer:
#      acks: all
#      batch-size: 16384
#      buffer-memory: 33554432
#      retries: 0
#      linger-ms: 1
#    properties:
#      sasl:
#        mechanism:
    ssl:
      truststore-location: src/main/resources/truststore.jks
      truststore-password: changeit
  logging:
    level:
      ROOT: DEBUG