spring:
  application.name: intverse-kafka-producer
  kafka:
    bootstrap-servers: redpanda-0.redpanda.aws.intverse.io:31092,redpanda-1.redpanda.aws.intverse.io:31092,redpanda-2.redpanda.aws.intverse.io:31092
    topic: intverse-topic
    producer:
      acks: all
      batch-size: 16384
      retries: 10
      linger-ms: 1
    properties:
      sasl:
        mechanism: SCRAM-SHA-512
        username: intverseuser
        password: intverse123
      security:
        protocol: SASL_SSL
    ssl:
      type: JKS
      algorithm: https
      client-auth: required
      truststore-location: src/main/resources/truststore.jks
      truststore-password: changeit
  logging:
    level:
      ROOT: TRACE

server:
  port: 8081